### ISSUE TITLE
Mousover affect on tables in callouts

### ISSUE THREAD

**Issue by Craftidore** [dbarenholz/halcyon-obsidian#3]
When you have a callout with a table, there's a mouse-over effect on the odd headers

With mouseover:

![2023-10-13-151522_861x158_scrot](https://github.com/dbarenholz/halcyon-obsidian/assets/73705352/2f6c6ec3-0bbf-44e1-a2da-57d4df84bc10)

Without mouseover:

![2023-10-13-151514_851x158_scrot](https://github.com/dbarenholz/halcyon-obsidian/assets/73705352/ac9d3e90-d1cd-4c77-a86f-c14c34c1a99b)

Markdown:

```md

> [!info]
> | test | Test | [[Testing-Note]] | test | 
> | ---- | ---- | ---------------- | --- |
> | test | test | test             | tes |

```

**Comment by dbarenholz** [comment]
Latest version should work now!
