### ISSUE TITLE
Canvas Selection Tool invisible

### ISSUE THREAD

**Issue by Craftidore** [dbarenholz/halcyon-obsidian#4]
When drag-selecting in a canvas, the selected-area square is invisible (though the currently selected canvas cards _are_ highlighted so you can still tell what's been selected)

**Comment by Craftidore** [comment]
![2023-10-13-161454_991x489_scrot](https://github.com/dbarenholz/halcyon-obsidian/assets/73705352/f3cfe124-b69b-4998-9274-3bec2620029d)

vs

![2023-10-13-161436_802x439_scrot](https://github.com/dbarenholz/halcyon-obsidian/assets/73705352/ce9b3b6c-434c-4ace-974f-a97574dc23e0)

**Comment by dbarenholz** [comment]
Figured out the cause! Selecting now works nicely.

![image](https://github.com/dbarenholz/halcyon-obsidian/assets/25849034/0dc8bdae-de4b-43ad-a5e8-417520650da0)

The cause: `--accent-s` and `--accent-l` CSS variables take _percentages_, not _numbers_.

Will take some time to consolidate changes before pushing, as this affects the entire theme everywhere.

**Comment by dbarenholz** [comment]
Fixed! New release: https://github.com/dbarenholz/halcyon-obsidian/releases/tag/0.0.3
