### ISSUE TITLE
[FR] Custom Checkboxes

### ISSUE THREAD

**Issue by sigrunixia** [dbarenholz/halcyon-obsidian#9]
You read me. Custom Checkboxes!

**Comment by dbarenholz** [comment]
Can you elaborate on which custom checkboxes you'd like to see Halcyon support?

**Comment by sigrunixia** [comment]
Let me look into what Halcyon typically does and has as themes, and I'll report back.

**Comment by sigrunixia** [comment]
So no one has made checkboxes for Halcyon before. Thus, pulling some common checkboxes from the main discord below.

I think we can take the most common ones that YOU would use, and Halcyonify them with the theme colors. 

Example: Question could be this icon in #ef6b73. https://game-icons.net/1x1/lorc/uncertainty.html

## Checkboxes so far

[!] Important - #c3a6ff
[?] Question - #ef6b73
[-] Cancelled - #6679a4
[rev] Review or Revise - #ffae57
[star] Star - #ffcc66
[todo] todo - #bae67e
[>>] Explanation - #5ccfe6

## Inspiration
![image](https://github.com/dbarenholz/halcyon-obsidian/assets/68425372/67fddcf5-b6dc-47c1-b1b3-331d7ce22ada)

![image](https://github.com/dbarenholz/halcyon-obsidian/assets/68425372/09a4cf2e-1469-49e4-af3e-9bd0812df39f)

**Comment by dbarenholz** [comment]
> I think we can take the most common ones that YOU would use, and Halcyonify them with the theme colors.

The reason why I ask which ones you'd want, is because I don't use any.

> Checkboxes so far

Can I assume this is the list you'd like to see in Halcyon?

**Comment by sigrunixia** [comment]
After making my own checkboxes, and talking with the Prism theme dev, I think we should err on the side of letting users add their own checkboxes.
